# Generated by Django 6.0.3 on 2026-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='next_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
