# Generated by Django 6.0.3 on 2026-03-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_customuser_telegram_chat_id_habit_next_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='connected_habit',
            field=models.ForeignKey(blank=True, limit_choices_to={'habit_type': 'полезная'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_from', to='habit_tracker.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('полезная', 'Полезная'), ('приятная', 'Приятная')], max_length=10),
        ),
    ]
